avatar: https://img-blog.csdnimg.cn/78ebd04c9eb54d858b4aa57f4f13c04b.png # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
    path: https://s2.loli.net/2022/06/11/wfuTIV7gaJpjBC2.png
    # path: /img/1.jpg
    width: 1280
    height: 726
favicon:
  href: https://s2.loli.net/2022/06/11/m1r7UeTHVh935ID.png # ç½‘ç«™å›¾æ ‡
  type: image/png # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  wordCount: true # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)
  fancybox: true # ç¯ç®±åŠŸèƒ½
  SmoothScroll: true # å¹³æ»‘æ»šåŠ¨
  pjax: false # Pjax æ— åˆ·æ–°åŠ è½½é¡µé¢ï¼Œæš‚æ—¶å­˜åœ¨è¾ƒå¤§é—®é¢˜
  # darkmode: true


imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½  
  origin: /../../images/ # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # å›¾ç‰‡ CDN åŸŸå

# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customStyles:
  - custom.css
  
# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib:  //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    å›åˆ°é¦–é¡µ:
        - /
        - icon-home
    åˆ†ç±»å½’æ¡£:
        - /archive.html
        - icon-container
    å­¦ä¹ ä¹‹è·¯:
        - /study/
        - icon-battlenet
    # æ€ç»´å¯¼å›¾:
    #     - /xmind
    #     - icon-coffee
    å…³äºåšä¸»:
        - /about.html
        - icon-info-circle

widgets:
    - name: hitokoto # ä¸€è¨€ widget
      enable: true
      options: 
        widgetHitokoto: # ä¸€è¨€ç»„ä»¶
            loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
            loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
            category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    
    - name: search
      enable: true
      options: 
        search: 
            type: local # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
            url: https://cn.bing.com/search?q=https://blog.csdn.net/weixin_42301220 # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
            id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ
    - name: social
      enable: true
      options: 
        social:

            GitHub:
                - https://github.com/CHH3213
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .1)

            CSDN:
                - https://blog.csdn.net/weixin_42301220
                - icon-rss
                - rgb(247, 132, 34)
                - rgba(247, 132, 34, .1)
            é‚®ç®±:
                - "mailto:1213472983@qq.com"
                - icon-mail-fill
                - rgb(29, 161, 242)
                - rgba(29, 161, 242, .1)
            # QQç¾¤: 
            #     - https://jq.qq.com/?_wv=1027&k=5CfKHun
            #     - icon-QQ
            #     - rgb(249, 174, 8)
            #     - rgba(249, 174, 8, .1)
            # å“”å“©å“”å“©:
            #     - https://space.bilibili.com/20238211
            #     - icon-bilibili
            #     - rgb(231, 106, 141)
            #     - rgba(231, 106, 141, .1)
    - name: category
      enable: false
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 17  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
            archive_type: 'year' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
            show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡
    - name: recent_posts
      enable: true
    - name: link #settings: widgetLink
      enable: false
      options: 
        widgetLink: #é“¾æ¥ç»„ä»¶
            - title: å°èˆ’åŒå­¦
              img: https://xsm.nexmoe.com/images/Infinite/Snipaste_2022-05-18_20-46-50.png
              link : https://xiaoshu.app/




copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

slotHead: ''

slotFooter: '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2058306854838448" crossorigin="anonymous"></script>'

# # è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
# slotSidebar: '<br><a target="_blank" href="https://beian.miit.gov.cn/">é„‚ICPå¤‡2020018486å·</a>
#     <br><a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">
#     <img src="https://i.dawnlab.me/c0268c1e6cfd0863d6ba35be1575941a.png" width="150px"></a>'



# ç»Ÿè®¡ç³»ç»Ÿï¼Œç›®å‰æ”¯æŒ Google analytics.js ç»Ÿè®¡ã€Google Tag Manager ç»Ÿè®¡ã€CNZZ ç»Ÿè®¡ã€è…¾è®¯ç»Ÿè®¡ã€51.Laç»Ÿè®¡ã€ç™¾åº¦ç»Ÿè®¡
analytics: 
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
  mdui:
    css: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/css/mdui.min.css
    js: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/js/mdui.min.js
  jquery:
    js: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js
  fancybox:
    css: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  SmoothScroll:
    js: https://cdn.jsdelivr.net/npm/smoothscroll-for-websites@1.4.9/SmoothScroll.min.js
  pjax:
    js: //cdn.jsdelivr.net/npm/pjax@0.2.8/pjax.min.js
  lazysizes:
    js: https://cdn.jsdelivr.net/npm/lazysizes@5.1.0/lazysizes.min.js
  highlight:
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.16.2/styles/atom-one-dark.css
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine@1.3.9/dist/Valine.min.js  

# cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
#   disqusjs: 
#     css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
#     js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
#   gitalk:
#     css: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.css
#     js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
#   valine:
#     js: https://cdn.jsdelivr.net/npm/valine

# è¯„è®ºæ¡†æ’æ§½
slotComment: gitment # è¯„è®ºæ¡†ï¼Œç›®å‰æ”¯æŒ gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot
# gitalk:
#   admin: nexmoe # æ‹¥æœ‰å¯¹è¯¥repoè¿›è¡Œæ“ä½œçš„ GitHub username
#   owner: nexmoe # æŒæœ‰è¯¥ repo çš„ GitHub username
#   repo: nexmoe.github.io # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
#   clientID: xxx # GitHub Client ID
#   clientSecret: xxx # GitHub Client Secret
gitment:
  enable: true
  owner: CHH3213 # æŒæœ‰è¯¥ repo çš„ GitHub username
  repo: CHH3213.github.io # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
  clientID: 55ea9dc4a0241f57729b # GitHub Client ID
  clientSecret: 20342a99dc08db6dbaa9d696c38404352353ad3a # GitHub Client Secret
  # lazy: true

# Math Equations Render Support
math:
  enable: true
  per_page: true
  engine: mathjax

slotCopyright: '<strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯'

# slotArticleEnd: '<p><img data-fancybox="gallery" src="https://i.dawnlab.me/53a8c7cf3ad77a0f0a456ce2c6afe88a.png" 
# alt="53a8c7cf3ad77a0f0a456ce2c6afe88a.png" data-caption="53a8c7cf3ad77a0f0a456ce2c6afe88a.png" loading="lazy"></p>'



